### ISSUE TITLE
how can I fix this issue ?? (ReferenceError: unity is not defined )

### ISSUE THREAD

**Issue by pandoragate** [Snack-X/unity-unpacker#1]
when I use 'unity-unpacker [options] <.unity3d>'
It seem like operations but it print
 ...

 that's all
After a while, the following error is displayed.

ReferenceError: unity is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

**Comment by Snack-X** [comment]
I guess you were using **Node.js REPL**. `unity-unpacker` command should be run at **CLI**.

And FYI, I have updated some details to README:
> This is not an universal unity unpacker, but designed for [some specific game](http://cinderella.idolmaster.jp/sl-stage/). If you are going to unpack *other game*'s resource files and *other game* is using Unity `5.1.2f`, it may work. Otherwise, it might not work.
